name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - uses: actions/checkout@v3

      # this sucks for building runtimes
      - uses: detjensrobert/flatpak-github-actions/flatpak-builder@flatpak-type
        with:
          bundle: org.freedesktop.Platform.GStreamer.openmpt.flatpak
          manifest-path: org.freedesktop.Platform.GStreamer.openmpt.yaml
