name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - uses: actions/checkout@v3

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: gstreamer-openmpt.flatpak
          manifest-path: org.freedesktop.Platform.GStreamer.openmpt.yaml
          cache-key: flatpak-builder-${{ github.sha }}
